language: ruby
addons:
  postgresql: '9.4'
rvm:
  - 2.2.5
before_install:
   - gem install bundler -v 1.9.10
script:
  - bundle exec rspec
before_script:
  - psql -c 'create database grape-doorkeeper_test' -U postgres
  - bundle exec rake db:structure:load
cache: bundler
notifications:
  email:
    on_success: never